### ISSUE TITLE
  File "uds.py", line 545, in <module>  

### ISSUE THREAD

**Issue by bobingtion** [stewartmcgown/uds#32]
was working just fine then this happened tried deleting everything and re download the program and tried different google account  
E:\download\uds-master>python uds.py
Traceback (most recent call last):
  File "uds.py", line 545, in <module>
    main()
  File "uds.py", line 438, in main
    uds = UDS()
  File "uds.py", line 49, in __init__
    self.api = GoogleAPI()
  File "E:\download\uds-master\API.py", line 31, in __init__
    self.reauth()
  File "E:\download\uds-master\API.py", line 37, in reauth
    creds = store.get()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by stewartmcgown** [comment]
Looks like an issue with Google oauth, are all the files you need still
there; credentials, client secret etc

**Comment by bobingtion** [comment]
yes it is https://imgur.com/a/Qh88LOv

**Comment by Mr-Schneider** [comment]
I am still having this issue. I have downloaded the credentials.json from google, manually copied the file to client_secret.json as well because running `python3 uds.py` gave me the same error. Is this the correct format?

```
{
   "installed":{
      "client_id":"randomstringhere.apps.googleusercontent.com",
      "project_id":"quickstart-numbershere",
      "auth_uri":"https://accounts.google.com/o/oauth2/auth",
      "token_uri":"https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
      "client_secret":"securecharactershere",
      "redirect_uris":[
         "urn:ietf:wg:oauth:2.0:oob",
         "http://localhost"
      ]
   }
}
```
