### ISSUE TITLE
Can't run initial setup

### ISSUE THREAD

**Issue by pantuts** [stewartmcgown/uds#50]
Traceback (most recent call last):
  File "uds.py", line 533, in <module>
    main()
  File "uds.py", line 426, in main
    uds = UDS()
  File "uds.py", line 50, in __init__
    self.api = GoogleAPI()
  File "/Users/pantuts/Apps/uds/API.py", line 31, in __init__
    self.reauth()
  File "/Users/pantuts/Apps/uds/API.py", line 37, in reauth
    creds = store.get()
  File "/Users/pantuts/Library/Python/3.7/lib/python/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/Users/pantuts/Library/Python/3.7/lib/python/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/Users/pantuts/Library/Python/3.7/lib/python/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by SammyHass** [comment]
Did you change the credentials.json file to be called client_secret.json and did you run the initial setup too.

I had this same message, hadn't done the first of the above when it happened.

**Comment by stewartmcgown** [comment]
SammyHass has explained the problem, you must follow the instructions or it won't work.

**Comment by pantuts** [comment]
Pls don't close this. What sammyHass said, i did it the very first time. Still error.

**Comment by stephaun** [comment]
I also am experiencing this issue.
I followed the instructions and named the file `client_secret.json` , then ran it and received the message:
```
/usr/local/lib/python3.5/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
```

So I then ran ``` cp client_secret.json credentials.json ``` and re-ran ``` python3 uds.py ``` and am now receiving the same "_module" error.
