### ISSUE TITLE
win10 error

### ISSUE THREAD

**Issue by bigsuperangel** [stewartmcgown/uds#51]
when i run python uds.py ,error :
$ python uds.py
Traceback (most recent call last):
  File "uds.py", line 533, in <module>
    main()
  File "uds.py", line 426, in main
    uds = UDS()
  File "uds.py", line 50, in __init__
    self.api = GoogleAPI()
  File "D:\develop\running\workspace_python\uds\API.py", line 31, in __init__
    self.reauth()
  File "D:\develop\running\workspace_python\uds\API.py", line 37, in reauth
    creds = store.get()
  File "C:\Users\linyu\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\linyu\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\linyu\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

**Comment by pantuts** [comment]
Duplicate #50

**Comment by stewartmcgown** [comment]
Please look at previous issues before submitting.
