### ISSUE TITLE
Python 3 uds.py shows ERROR!

### ISSUE THREAD

**Issue by dkb007** [stewartmcgown/uds#88]
OS : Windows 10
Python Version : Python 3.8.0

I have installed the requirements using the command : pip3 install -r requirements.txt
then when I tried to run the command Python3 uds.py, it shows the error : 

//Error 
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 uds.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

But When I tried to use the command ./uds.py it opens a blank cmd window for a second and then that cmd window closes itself and nothing happens in the Powershell.

I had a quick search on google and the answers told me to add the PATH of the Python3.8 to your Environment Variables and I have done that also but still same problem occurs.

Other answer suggest to run python instead of python3 so I tried that also but it shows : 

//Error
Traceback (most recent call last):
  File "uds.py", line 534, in <module>
    main()
  File "uds.py", line 452, in main
    uds = UDS()
  File "uds.py", line 46, in __init__
    self.api = GoogleAPI()
  File "C:\Users\Devarsh\Desktop\uds-master\api.py", line 19, in __init__
    self.reauth()
  File "C:\Users\Devarsh\Desktop\uds-master\api.py", line 25, in reauth
    credentials = store.get()
  File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

I know that it's for python 3 so using just python is not going to work, but I cannot find a proper solution to run that uds.py file in the Powershell

**Comment by innowebka** [comment]
> 
> 
> OS : Windows 10
> Python Version : Python 3.8.0
> 
> I have installed the requirements using the command : pip3 install -r requirements.txt
> then when I tried to run the command Python3 uds.py, it shows the error :
> 
> //Error
> python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> 
>     * python3 uds.py
> 
>     * ```
>         + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
>         + FullyQualifiedErrorId : CommandNotFoundException
>       ```
> 
> 
> But When I tried to use the command ./uds.py it opens a blank cmd window for a second and then that cmd window closes itself and nothing happens in the Powershell.
> 
> I had a quick search on google and the answers told me to add the PATH of the Python3.8 to your Environment Variables and I have done that also but still same problem occurs.
> 
> Other answer suggest to run python instead of python3 so I tried that also but it shows :
> 
> //Error
> Traceback (most recent call last):
> File "uds.py", line 534, in
> main()
> File "uds.py", line 452, in main
> uds = UDS()
> File "uds.py", line 46, in **init**
> self.api = GoogleAPI()
> File "C:\Users\Devarsh\Desktop\uds-master\api.py", line 19, in **init**
> self.reauth()
> File "C:\Users\Devarsh\Desktop\uds-master\api.py", line 25, in reauth
> credentials = store.get()
> File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\client.py", line 407, in get
> return self.locked_get()
> File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\file.py", line 54, in locked_get
> credentials = client.Credentials.new_from_json(content)
> File "C:\Users\Devarsh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
> module_name = data['_module']
> KeyError: '_module'
> 
> I know that it's for python 3 so using just python is not going to work, but I cannot find a proper solution to run that uds.py file in the Powershell

**must install python 3.7.3 to work**

**Comment by ThatIsAPseudo** [comment]
Check whether the file is minified or not. Mine was on a single line and it did not work, I beautified it and the error disappeared.

**Comment by 78Alpha** [comment]
For windows you should use :

py -3 uds.py

python3 is for *nix systems and certain IDE environments to run python files
