### ISSUE TITLE
KeyError: '_module'

### ISSUE THREAD

**Issue by max326-coder** [stewartmcgown/uds#95]
PS C:\Users\Dhaval\Downloads\uds-master> python3 uds.py push ~\Desktop\ffmpeg.exe
Traceback (most recent call last):
  File "uds.py", line 534, in <module>
    main()
  File "uds.py", line 452, in main
    uds = UDS()
  File "uds.py", line 46, in __init__
    self.api = GoogleAPI()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 19, in __init__
    self.reauth()
  File "C:\Users\Dhaval\Downloads\uds-master\api.py", line 25, in reauth
    credentials = store.get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Users\Dhaval\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'

help me out please reply me

**Comment by OmarElKhatibCS** [comment]
Hello try to use an envirement , virtualenv or any thing like this .

**Comment by 78Alpha** [comment]
Tested this out, the error does pop up. Some forums say it has to do with quickstart, but this seems less like the case.

After installing the requirements manually, and installing the required elements from step 2 of the google guide, my Python3 install was able to run it (I can not verify much beyond that as I have 5 installs spaghettified together...)

So, try installing with a specific interpreter, the requirements one by one (py -3.8 -m pip install X Y Z)

**Comment by LoipesMas** [comment]
For me the problem was that when I downloaded the client secret from google's api it saved as credentials.json, so i moved it to uds folder and copied it to client_secret.json. This left old credentials.json file, which uds api needs to be something else. 
Deleting credentials.json fixed it for me.
